### ISSUE TITLE
Disentanglement metric

### ISSUE THREAD

**Issue by DaddyWesker** [1Konny/Beta-VAE#5]
Hello. 

Haven't found it in your code. Is there d.metric in it somewhere?

Thanks in advance

**Comment by 1Konny** [comment]
No. currently code for quantitative disentanglement metric is not included in this repo.

**Comment by DaddyWesker** [comment]
Oh well... Then i should write it myself. Thanks!

**Comment by bliiink182** [comment]
I am about to implement it as well. I was wondering if you finished your implementation or are interested in my results.

**Comment by DaddyWesker** [comment]
Well, i have tried to. But got not so good results, perhaps i was wrong. Then, my superior sent me to do some other work so i hadn't any possibility to make that since then... So if you will implement this metric it will be really good and i'm interested.
